name: repo_variable _demo.yml
on:
  workflow_dispatch:
    inputs:  #input environment
      environment:
        description: Deployment Environment
        required: true
        default: Development

jobs:
#call repo Variable
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Variable
        run: echo "${{vars.APP_NAME}}"
#input envionment call
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo"Building.."

      - name: Deploy
        if: github.ref_name == 'master'
        run: echo "Deploying to ${{inputs.environment}}"

#GitHub Contexts
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository = ${{github.repository}}"
      - run: echo "Branch = ${{github.ref_name}}"
      - run: echo "Triggered By = ${{github.actor}}"
      - run: echo "Workflow = ${{github.workflow}}"
