name: repo_variable _demo.yml
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment Environment
        required: true
        default: Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Variable
        run: echo "${{vars.APP_NAME}}"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{inputs.environment}}"
