name: Workflow Level Variable Demo

on:
  workflow_dispatch:

env:
  APP_NAME: Employee Service

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: 21

    steps:
      - name: Print Application Name
        run: echo "Application= $APP_NAME"

      - name: Print Java
      - run: echo "Java Version= $JAVA_VERSION"
      - run: java -version